# Generated by Django 3.2.4 on 2021-07-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=100)),
                ('LName', models.CharField(max_length=100)),
                ('Role', models.CharField(default='Reception Admin', max_length=50, null=True)),
                ('Address', models.CharField(max_length=100)),
                ('EmailId', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('RegistrationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
