# Generated by Django 3.2.4 on 2021-07-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Role', models.CharField(default='Doctor', max_length=50, null=True)),
                ('BirthDay', models.DateField(auto_now_add=True)),
                ('Address', models.CharField(max_length=300, null=True)),
                ('Phone_Number', models.CharField(max_length=12, null=True)),
                ('Gender', models.CharField(choices=[('Gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=6)),
                ('Department', models.CharField(choices=[('Departments', 'Departments'), ('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Departments', max_length=150)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('ProfilePic', models.FileField(blank=True, null=True, upload_to='assets/images/doctors')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('DStatus', models.CharField(choices=[('Active', 'ACTIVE'), ('Deactive', 'DEACTIVE')], default=True, max_length=100)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reception.user')),
            ],
        ),
    ]
