# Generated by Django 3.2.4 on 2021-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='OTP',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
