# Generated by Django 3.2.4 on 2021-07-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctor_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='OTP',
        ),
    ]
