# Generated by Django 3.2.4 on 2021-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_remove_doctor_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Phone_Number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Role',
            field=models.CharField(default='Doctor', max_length=50),
        ),
    ]
