# Generated by Django 3.2.4 on 2021-07-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20210704_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='User',
            new_name='user',
        ),
    ]
