# Generated by Django 3.2.4 on 2021-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_alter_doctor_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ProfilePic',
            field=models.ImageField(default='none.jpg', upload_to='Doctor/Profile/'),
        ),
    ]
