# Generated by Django 3.2.4 on 2021-07-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patients', '0002_appointments_doctorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppointmentDate', models.DateField(auto_now=True)),
                ('Description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('DoctorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('PatientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patients.patients')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
