# Generated by Django 3.2.4 on 2021-07-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_auto_20210701_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeappointments',
            old_name='DoctorId',
            new_name='DoctorsId',
        ),
    ]
