# Generated by Django 3.2.4 on 2021-07-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_rename_doctorid_takeappointments_doctorsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeappointments',
            old_name='DoctorsId',
            new_name='DoctorId',
        ),
    ]
