# Generated by Django 3.2.4 on 2021-07-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0006_rename_takeappointments_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='Description',
            new_name='Discription',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='status',
            new_name='Status',
        ),
    ]
