# Generated by Django 3.2.4 on 2021-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_auto_20210701_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Aprove', 'Aprove'), ('Reject', 'Reject')], default='Pending', max_length=30, null=True),
        ),
    ]
