# Generated by Django 3.2.4 on 2021-07-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_alter_doctor_dstatus'),
        ('Patients', '0010_rename_user_patients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='DoctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], default='Pending', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], default='Pending', max_length=30, null=True),
        ),
    ]
