# Generated by Django 3.2.4 on 2021-07-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_alter_doctor_profilepic'),
        ('Reception', '0003_alter_user_role'),
        ('Patients', '0011_auto_20210711_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargePatients',
            fields=[
                ('Bill_Number', models.BigAutoField(default=True, primary_key=True, serialize=False)),
                ('releaseDate', models.DateField(auto_now_add=True)),
                ('RoomCharge', models.PositiveIntegerField(default=0)),
                ('MedicineCost', models.PositiveIntegerField(default=0)),
                ('DoctorFee', models.PositiveIntegerField(default=0)),
                ('OtherCharge', models.PositiveIntegerField()),
                ('Total', models.PositiveIntegerField(default=0)),
                ('DoctorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('PatientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patients.patients')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reception.user')),
            ],
        ),
        
    ]
