# Generated by Django 3.2.4 on 2021-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0012_dischargepatients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargepatients',
            name='Bill_Number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
