# Generated by Django 3.2.4 on 2021-07-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0013_alter_dischargepatients_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargepatients',
            old_name='releaseDate',
            new_name='ReleaseDate',
        ),
    ]
