# Generated by Django 3.2.4 on 2021-07-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0014_rename_releasedate_dischargepatients_releasedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargepatients',
            old_name='ReleaseDate',
            new_name='PaymentDate',
        ),
    ]
