# Generated by Django 3.2.4 on 2021-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0015_rename_releasedate_dischargepatients_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
